databases:
  - name: furgo
    plan: free
    databaseName: furgo_hh0t
    user: furgo_hh0t_user

services:
  - type: web
    plan: free
    name: furgo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn FurGo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: furgo_hh0t
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: WEB_CONCURRENCY
        value: 4
